### PR TITLE
Added comments to the android lint analyzer, and fixed a bug with it not...

### PR DESCRIPTION
**Pull request by ciera**
... displaying the output.

### CODE REVIEW

**Comment by ciera** [comment]
ping

**Comment by clconway** [comment]
Sorry I dropped this. I'm not sure I even noticed I was assigned and AFAICT there's no dashboard for my incoming PRs?

**Comment by clconway** [comment]
Do you need to rebase against master or will clicking merge automatically take care of my commits that are already there?

**Comment by ciera** [comment]
There is not. There is also no way for me to respond directly to comments. Though, I can edit your comment...so there's that...

I did pull and rebase from master, but the pull should merge everyhting properly.

**Pull request merged**
